# # Use the latest 2.1 version of CircleCI pipeline process engine.
# # See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10
  ruby: circleci/ruby@2.1.2

jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.2
      - environment:
          POSTGRES_DB: favorited_recipes_service_test
          POSTGRES_USER: postgres
        image: circleci/postgres:9.5-alpine
    environment:
      PGHOST: 127.0.0.1
      PGPASSWORD: ''
      PGUSER: postgres
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps  # Uses the ruby orb to install dependencies
      - run:
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
          name: Wait for DB
      - run:
          command: bundle exec rails db:schema:load --trace
          name: Database setup
      - ruby/rspec-test:
          include: spec/**/*_spec.rb

workflows:
  version: 2
  run_tests_and_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: main