# # Use the latest 2.1 version of CircleCI pipeline process engine.
# # See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
  ruby: circleci/ruby@2.1.2
jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.2
  steps:
    - run:
        command: bundle exec rspec

workflows:
  run_tests:
    jobs:
      - build
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git