# # Use the latest 2.1 version of CircleCI pipeline process engine.
# # See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10
  ruby: circleci/ruby@2.1.2

workflows:
  heroku_deploy:
      jobs:
        - heroku/deploy-via-git:
          post-steps:
              - run: rails db:migrate